import "dotenv/config";
import { db } from "./db";
import { TicketStatus } from "./generated/prisma/client";

const SUBROTO = "72798743-eb6c-43f4-8529-c361c69b7644";
const GOUTOM = "320865d3-ffc5-4c24-a894-7d4b99dbd2ca";

const daysAgo = (n: number): Date => {
  const d = new Date();
  d.setDate(d.getDate() - n);
  return d;
};

type RawTicket = {
  subject: string;
  body: string;
  senderName: string;
  senderEmail: string;
  status: TicketStatus;
  category: string;
  daysAgo: number;
  assignedToId: string | null;
};

const tickets: RawTicket[] = [
  // ── Billing (15) ──────────────────────────────────────────────────────────
  {
    subject: "Invoice #4821 shows incorrect amount",
    body: "Hello,\n\nI noticed that invoice #4821 issued on 28 April shows $349 but our agreed price is $299/month. Could you issue a corrected invoice?\n\nThanks,\nJames",
    senderName: "James Carter",
    senderEmail: "james.carter@acme.com",
    status: TicketStatus.open,
    category: "Billing",
    daysAgo: 3,
    assignedToId: null,
  },
  {
    subject: "Charged twice for March subscription",
    body: "Hi support,\n\nI can see two charges of $99 on my credit card statement for March (3rd and 4th March). Please refund the duplicate charge.\n\nRobert Kim",
    senderName: "Robert Kim",
    senderEmail: "r.kim@globex.net",
    status: TicketStatus.inProgress,
    category: "Billing",
    daysAgo: 12,
    assignedToId: SUBROTO,
  },
  {
    subject: "Need VAT invoice for Q1 payments",
    body: "Hello,\n\nOur accounting department requires VAT-compliant invoices for January, February, and March payments. Our VAT number is EU826541032. Could you regenerate these with VAT details?\n\nLisa Chen",
    senderName: "Lisa Chen",
    senderEmail: "lchen@enterprise.co",
    status: TicketStatus.closed,
    category: "Billing",
    daysAgo: 45,
    assignedToId: GOUTOM,
  },
  {
    subject: "Cannot access billing portal",
    body: "I click on 'Billing' in the account menu and the page returns a blank white screen. Chrome 124 on Windows 11. Cleared cache, same result.\n\nJessica Brown",
    senderName: "Jessica Brown",
    senderEmail: "jbrown@finance.com",
    status: TicketStatus.open,
    category: "Billing",
    daysAgo: 1,
    assignedToId: null,
  },
  {
    subject: "Refund not received after 14 days",
    body: "Hi,\n\nI cancelled my subscription on April 8th and was told the refund would arrive within 5–7 business days. It is now 14 days later and nothing has appeared. Transaction ID: TXN-2024-98231.\n\nAmanda Foster",
    senderName: "Amanda Foster",
    senderEmail: "afoster@retail.com",
    status: TicketStatus.inProgress,
    category: "Billing",
    daysAgo: 8,
    assignedToId: SUBROTO,
  },
  {
    subject: "Upgrade to annual plan – discount applies?",
    body: "Hello,\n\nWe have been on the monthly Pro plan for 4 months. If we switch to annual now, does the 20% discount apply to the remaining months or only from the renewal date?\n\nEmily Watson",
    senderName: "Emily Watson",
    senderEmail: "ewatson@startupxyz.com",
    status: TicketStatus.closed,
    category: "Billing",
    daysAgo: 60,
    assignedToId: GOUTOM,
  },
  {
    subject: "Card declined but account shows active",
    body: "My card was declined when trying to update payment details, yet the account dashboard still shows 'Active'. I'm worried about a billing gap. The card is valid and has sufficient funds.\n\nMichael Torres",
    senderName: "Michael Torres",
    senderEmail: "mtorres@consulting.biz",
    status: TicketStatus.open,
    category: "Billing",
    daysAgo: 2,
    assignedToId: null,
  },
  {
    subject: "Wrong currency charged (USD instead of EUR)",
    body: "We are based in Germany and our account is set to EUR, but the latest invoice was charged in USD causing an unwanted currency conversion. Please adjust billing to EUR and refund the exchange fee.\n\nThomas Wright",
    senderName: "Thomas Wright",
    senderEmail: "t.wright@logistics.net",
    status: TicketStatus.inProgress,
    category: "Billing",
    daysAgo: 15,
    assignedToId: SUBROTO,
  },
  {
    subject: "Request invoice for tax filing",
    body: "Hi,\n\nCould you please send invoices for all transactions made between January 1st and December 31st 2024? We need them for our annual tax return. PDF format preferred.\n\nMaria Lopez",
    senderName: "Maria Lopez",
    senderEmail: "mlopez@education.edu",
    status: TicketStatus.closed,
    category: "Billing",
    daysAgo: 90,
    assignedToId: GOUTOM,
  },
  {
    subject: "Prorated charge after plan downgrade unclear",
    body: "I downgraded from Business to Starter on the 15th of the month. The invoice shows a prorated credit but the math doesn't add up — I was charged $47 when I expected ~$23. Can you walk me through the calculation?\n\nDavid Park",
    senderName: "David Park",
    senderEmail: "dpark@solutions.org",
    status: TicketStatus.open,
    category: "Billing",
    daysAgo: 5,
    assignedToId: null,
  },
  {
    subject: "Payment method update not saving",
    body: "Every time I try to update my credit card details the form spins for about 10 seconds and then shows 'Something went wrong'. The old card expires next week so this is urgent.\n\nSarah Mitchell",
    senderName: "Sarah Mitchell",
    senderEmail: "sarah.m@techcorp.io",
    status: TicketStatus.inProgress,
    category: "Billing",
    daysAgo: 10,
    assignedToId: SUBROTO,
  },
  {
    subject: "Subscription auto-renewed without notice",
    body: "Hello,\n\nI did not receive any renewal reminder before my annual subscription was charged yesterday. Your terms say a 30-day notice email is sent. Please check and refund if the notice was not sent.\n\nRachel Green",
    senderName: "Rachel Green",
    senderEmail: "rgreen@media.co",
    status: TicketStatus.open,
    category: "Billing",
    daysAgo: 2,
    assignedToId: null,
  },
  {
    subject: "Credits not applied to latest invoice",
    body: "Hi team,\n\nWe have $50 in account credits from a referral but the latest invoice for $199 was charged in full without applying those credits. Ticket #3841 from last month confirmed the credit was added.\n\nKevin Anderson",
    senderName: "Kevin Anderson",
    senderEmail: "kanderson@healthcare.org",
    status: TicketStatus.closed,
    category: "Billing",
    daysAgo: 70,
    assignedToId: GOUTOM,
  },
  {
    subject: "Trial period ended before 14 days",
    body: "I signed up for a 14-day free trial on April 20th but my account was charged on April 28th — only 8 days in. Please refund the charge and restore my trial days.\n\nChris Nguyen",
    senderName: "Chris Nguyen",
    senderEmail: "chris.n@agency.io",
    status: TicketStatus.open,
    category: "Billing",
    daysAgo: 4,
    assignedToId: null,
  },
  {
    subject: "Need to split invoice across two departments",
    body: "Hello,\n\nStarting next month we need our invoice split 60/40 between Engineering and Marketing cost centres, each with a separate PO number. Is this supported, and if so, how do we configure it?\n\nDaniel Scott",
    senderName: "Daniel Scott",
    senderEmail: "dscott@realestate.com",
    status: TicketStatus.inProgress,
    category: "Billing",
    daysAgo: 20,
    assignedToId: SUBROTO,
  },

  // ── Authentication (12) ───────────────────────────────────────────────────
  {
    subject: "Cannot reset password – email not received",
    body: "Hi,\n\nI requested a password reset three times and have not received any email. I have checked spam. My email address is james.carter@acme.com.\n\nJames Carter",
    senderName: "James Carter",
    senderEmail: "james.carter@acme.com",
    status: TicketStatus.open,
    category: "Authentication",
    daysAgo: 1,
    assignedToId: null,
  },
  {
    subject: "Two-factor authentication locked out",
    body: "I lost access to my authenticator app after getting a new phone and I can't log in. I have access to my backup codes but the system rejects them. Account email: sarah.m@techcorp.io\n\nSarah Mitchell",
    senderName: "Sarah Mitchell",
    senderEmail: "sarah.m@techcorp.io",
    status: TicketStatus.inProgress,
    category: "Authentication",
    daysAgo: 6,
    assignedToId: SUBROTO,
  },
  {
    subject: "SSO login returns 'user not found' error",
    body: "Our company set up SSO via Okta last week. When employees try to log in they see 'User not found in system'. Our admin has verified the SAML attributes are being sent correctly.\n\nLisa Chen",
    senderName: "Lisa Chen",
    senderEmail: "lchen@enterprise.co",
    status: TicketStatus.open,
    category: "Authentication",
    daysAgo: 3,
    assignedToId: null,
  },
  {
    subject: "Google OAuth disconnected after password change",
    body: "After changing my Google password, the Google login button on your site shows 'Account not connected'. I don't want to use a separate password — can you re-link my Google account without losing my data?\n\nEmily Watson",
    senderName: "Emily Watson",
    senderEmail: "ewatson@startupxyz.com",
    status: TicketStatus.closed,
    category: "Authentication",
    daysAgo: 55,
    assignedToId: GOUTOM,
  },
  {
    subject: "Account suspended after failed login attempts",
    body: "I was locked out after entering my password incorrectly 5 times. The unlock link in the email takes me to a page that just says 'Link expired'. Please manually unlock my account.\n\nRobert Kim",
    senderName: "Robert Kim",
    senderEmail: "r.kim@globex.net",
    status: TicketStatus.inProgress,
    category: "Authentication",
    daysAgo: 9,
    assignedToId: SUBROTO,
  },
  {
    subject: "Login redirect loop on Safari",
    body: "When I try to log in using Safari 17 on macOS Sonoma, the page just keeps refreshing. I can log in fine on Chrome. I have disabled all extensions and the problem persists.\n\nAmanda Foster",
    senderName: "Amanda Foster",
    senderEmail: "afoster@retail.com",
    status: TicketStatus.open,
    category: "Authentication",
    daysAgo: 2,
    assignedToId: null,
  },
  {
    subject: "SAML configuration not working for new IdP",
    body: "We migrated from ADFS to Azure AD B2C. I have updated the metadata URL in your admin panel but login attempts return a generic '500 Internal Server Error'. Our old configuration is attached.\n\nKevin Anderson",
    senderName: "Kevin Anderson",
    senderEmail: "kanderson@healthcare.org",
    status: TicketStatus.inProgress,
    category: "Authentication",
    daysAgo: 14,
    assignedToId: SUBROTO,
  },
  {
    subject: "Password requirements not visible on signup form",
    body: "The signup page doesn't show any password requirements until after you submit. My password was rejected three times before I figured out a special character was required. Please add inline hints.\n\nChris Nguyen",
    senderName: "Chris Nguyen",
    senderEmail: "chris.n@agency.io",
    status: TicketStatus.closed,
    category: "Authentication",
    daysAgo: 100,
    assignedToId: GOUTOM,
  },
  {
    subject: "Session expires too quickly (under 10 minutes)",
    body: "My session is being logged out after approximately 8–10 minutes of inactivity even during a work day. This is causing me to lose unsaved form data. Our account should have the 8-hour session setting.\n\nJessica Brown",
    senderName: "Jessica Brown",
    senderEmail: "jbrown@finance.com",
    status: TicketStatus.open,
    category: "Authentication",
    daysAgo: 3,
    assignedToId: null,
  },
  {
    subject: "Cannot login on mobile app after web login",
    body: "If I'm logged in on the web, the mobile app (Android 14) shows 'Session conflict – please log out elsewhere'. But logging out on web just logs me out entirely. This makes using both impossible.\n\nThomas Wright",
    senderName: "Thomas Wright",
    senderEmail: "t.wright@logistics.net",
    status: TicketStatus.closed,
    category: "Authentication",
    daysAgo: 80,
    assignedToId: GOUTOM,
  },
  {
    subject: "Magic link email never arrives",
    body: "I use passwordless login and the magic link email is not arriving. Tested with Gmail and Outlook — both show nothing even after 15 minutes. Please check your email delivery status.\n\nMaria Lopez",
    senderName: "Maria Lopez",
    senderEmail: "mlopez@education.edu",
    status: TicketStatus.open,
    category: "Authentication",
    daysAgo: 1,
    assignedToId: null,
  },
  {
    subject: "Passkey enrollment fails on Windows Hello",
    body: "When I try to register a passkey via Windows Hello (Windows 11, Chrome 124) the dialog opens, I authenticate with my PIN, and then the page shows 'Registration failed'. Works fine on my MacBook.\n\nDaniel Scott",
    senderName: "Daniel Scott",
    senderEmail: "dscott@realestate.com",
    status: TicketStatus.inProgress,
    category: "Authentication",
    daysAgo: 18,
    assignedToId: SUBROTO,
  },

  // ── Technical (18) ────────────────────────────────────────────────────────
  {
    subject: "API rate limit hit unexpectedly at low usage",
    body: "Our integration is hitting the 429 rate limit after ~50 requests per minute. Our plan allows 500 RPM. Is there a per-endpoint limit not documented in the API docs?\n\nSarah Mitchell",
    senderName: "Sarah Mitchell",
    senderEmail: "sarah.m@techcorp.io",
    status: TicketStatus.open,
    category: "Technical",
    daysAgo: 2,
    assignedToId: null,
  },
  {
    subject: "Webhook not firing on ticket status change",
    body: "We configured a webhook for the ticket.status_changed event but it is never triggered when we update ticket status via the UI or API. The endpoint is reachable and returns 200 for test events.\n\nLisa Chen",
    senderName: "Lisa Chen",
    senderEmail: "lchen@enterprise.co",
    status: TicketStatus.inProgress,
    category: "Technical",
    daysAgo: 7,
    assignedToId: SUBROTO,
  },
  {
    subject: "CSV export contains garbled UTF-8 characters",
    body: "When exporting our customer list to CSV, any name with accented characters (é, ü, ñ) shows as question marks or boxes when opened in Excel. The raw file looks fine in a text editor.\n\nDavid Park",
    senderName: "David Park",
    senderEmail: "dpark@solutions.org",
    status: TicketStatus.closed,
    category: "Technical",
    daysAgo: 65,
    assignedToId: GOUTOM,
  },
  {
    subject: "Dashboard shows 504 Gateway Timeout after login",
    body: "Since this morning, after logging in successfully I am immediately shown a 504 Gateway Timeout page. This affects the entire team (6 users). Other pages like Settings load fine.\n\nJames Carter",
    senderName: "James Carter",
    senderEmail: "james.carter@acme.com",
    status: TicketStatus.open,
    category: "Technical",
    daysAgo: 1,
    assignedToId: null,
  },
  {
    subject: "API response time exceeds 10 seconds for bulk queries",
    body: "The GET /api/v2/tickets?limit=500 endpoint takes 10–15 seconds to respond. With limit=100 it is under 1 second. We need to fetch 2,000 records daily and this is becoming a bottleneck.\n\nKevin Anderson",
    senderName: "Kevin Anderson",
    senderEmail: "kanderson@healthcare.org",
    status: TicketStatus.inProgress,
    category: "Technical",
    daysAgo: 11,
    assignedToId: SUBROTO,
  },
  {
    subject: "Report generation fails for date ranges over 90 days",
    body: "Generating any report with a date range wider than 90 days shows a spinner for 30 seconds and then a generic 'Generation failed' message with no error code. Ranges under 90 days work fine.\n\nJessica Brown",
    senderName: "Jessica Brown",
    senderEmail: "jbrown@finance.com",
    status: TicketStatus.open,
    category: "Technical",
    daysAgo: 4,
    assignedToId: null,
  },
  {
    subject: "PDF export cuts off last column on A4 paper",
    body: "When we print the ticket list PDF on A4 paper the 'Assigned To' column is cut in half. The PDF itself looks fine on screen at 100% zoom. Issue happens on both Chrome and Firefox print dialogs.\n\nRachel Green",
    senderName: "Rachel Green",
    senderEmail: "rgreen@media.co",
    status: TicketStatus.closed,
    category: "Technical",
    daysAgo: 110,
    assignedToId: GOUTOM,
  },
  {
    subject: "Search returns no results for exact match",
    body: "Searching for 'invoice' returns no results even though I can see several tickets with that word in the subject. The issue started yesterday. Full-text search in filters is also affected.\n\nEmily Watson",
    senderName: "Emily Watson",
    senderEmail: "ewatson@startupxyz.com",
    status: TicketStatus.open,
    category: "Technical",
    daysAgo: 3,
    assignedToId: null,
  },
  {
    subject: "Notification emails contain broken image links",
    body: "The ticket notification emails we receive have broken image placeholders where your logo should appear. The image URLs point to https://cdn.example.com/... which returns 403 Forbidden.\n\nAmanda Foster",
    senderName: "Amanda Foster",
    senderEmail: "afoster@retail.com",
    status: TicketStatus.inProgress,
    category: "Technical",
    daysAgo: 13,
    assignedToId: SUBROTO,
  },
  {
    subject: "Mobile app crashes on iOS 18.2",
    body: "Your iOS app crashes immediately on launch after updating to iOS 18.2. Rolling back to 18.1 fixes the issue. App version is 4.3.1. I have sent the crash report to crashes@helpdesk.example.com.\n\nChris Nguyen",
    senderName: "Chris Nguyen",
    senderEmail: "chris.n@agency.io",
    status: TicketStatus.open,
    category: "Technical",
    daysAgo: 2,
    assignedToId: null,
  },
  {
    subject: "Bulk import fails silently for files over 5 MB",
    body: "When importing a CSV larger than 5 MB the progress bar reaches 100% but no records appear. There is no error message. Files under 5 MB import fine. Our daily import is typically 8–12 MB.\n\nMichael Torres",
    senderName: "Michael Torres",
    senderEmail: "mtorres@consulting.biz",
    status: TicketStatus.closed,
    category: "Technical",
    daysAgo: 75,
    assignedToId: GOUTOM,
  },
  {
    subject: "Date picker ignores user timezone",
    body: "I am in AEST (UTC+10). When I select 'today' in the date picker it stores the date as yesterday UTC. This causes all date-filtered reports to be off by one day for users outside UTC.\n\nThomas Wright",
    senderName: "Thomas Wright",
    senderEmail: "t.wright@logistics.net",
    status: TicketStatus.open,
    category: "Technical",
    daysAgo: 5,
    assignedToId: null,
  },
  {
    subject: "API key rotation breaks existing integrations",
    body: "When I rotated our API key using the 'Rotate' button in settings, the old key stopped working immediately. I expected a grace period. This broke our production integration for 2 hours.\n\nDaniel Scott",
    senderName: "Daniel Scott",
    senderEmail: "dscott@realestate.com",
    status: TicketStatus.inProgress,
    category: "Technical",
    daysAgo: 16,
    assignedToId: SUBROTO,
  },
  {
    subject: "Drag-and-drop file upload not working in Firefox",
    body: "Dragging a file onto the upload area works perfectly in Chrome but in Firefox 125 the file is opened in the browser tab instead of being uploaded. This affects all our design team who use Firefox.\n\nMaria Lopez",
    senderName: "Maria Lopez",
    senderEmail: "mlopez@education.edu",
    status: TicketStatus.open,
    category: "Technical",
    daysAgo: 2,
    assignedToId: null,
  },
  {
    subject: "Real-time updates stop after browser idle",
    body: "After leaving a ticket open for about 20 minutes without interaction, new replies no longer appear without a page refresh. Other users in the same thread see updates fine. Likely a WebSocket keep-alive issue.\n\nJames Carter",
    senderName: "James Carter",
    senderEmail: "james.carter@acme.com",
    status: TicketStatus.closed,
    category: "Technical",
    daysAgo: 130,
    assignedToId: GOUTOM,
  },
  {
    subject: "Custom fields not included in API response",
    body: "We have 4 custom fields configured ('Priority', 'Region', 'Product', 'SLA Level'). When we fetch tickets via the API these fields are absent from the JSON response even with ?include=custom_fields.\n\nSarah Mitchell",
    senderName: "Sarah Mitchell",
    senderEmail: "sarah.m@techcorp.io",
    status: TicketStatus.inProgress,
    category: "Technical",
    daysAgo: 9,
    assignedToId: SUBROTO,
  },
  {
    subject: "Sorting on the data table resets page to 1",
    body: "When I am on page 3 of the tickets list and click a column header to sort, the table jumps back to page 1 and I have to navigate back. Expected behaviour is to stay on the current page.\n\nRobert Kim",
    senderName: "Robert Kim",
    senderEmail: "r.kim@globex.net",
    status: TicketStatus.open,
    category: "Technical",
    daysAgo: 4,
    assignedToId: null,
  },
  {
    subject: "Print view missing header and footer",
    body: "Printing any page using Ctrl+P removes the navigation header and page footer that would help identify the printed document. Competitors show a minimal print header. Is this on the roadmap?\n\nLisa Chen",
    senderName: "Lisa Chen",
    senderEmail: "lchen@enterprise.co",
    status: TicketStatus.closed,
    category: "Technical",
    daysAgo: 85,
    assignedToId: GOUTOM,
  },

  // ── Account (10) ─────────────────────────────────────────────────────────
  {
    subject: "Need to transfer account ownership to new admin",
    body: "Our previous admin (john.doe@acme.com) left the company. We need to transfer ownership to james.carter@acme.com. I can provide verification of employment. Please advise the process.\n\nJames Carter",
    senderName: "James Carter",
    senderEmail: "james.carter@acme.com",
    status: TicketStatus.inProgress,
    category: "Account",
    daysAgo: 8,
    assignedToId: SUBROTO,
  },
  {
    subject: "Cannot delete deactivated team members",
    body: "I deactivated two former employees but the 'Delete' button on their profiles is greyed out. The tooltip says 'Contact support to permanently delete users'. Please delete accounts for j.doe@acme.com and t.smith@acme.com.\n\nEmily Watson",
    senderName: "Emily Watson",
    senderEmail: "ewatson@startupxyz.com",
    status: TicketStatus.open,
    category: "Account",
    daysAgo: 3,
    assignedToId: null,
  },
  {
    subject: "Profile picture upload returns 413 error",
    body: "When I try to upload a profile picture I get a 413 Request Entity Too Large error. The image is 800KB and in JPEG format — well within any reasonable limit. Other users report the same.\n\nDavid Park",
    senderName: "David Park",
    senderEmail: "dpark@solutions.org",
    status: TicketStatus.closed,
    category: "Account",
    daysAgo: 50,
    assignedToId: GOUTOM,
  },
  {
    subject: "Email address change not reflecting in reports",
    body: "I updated my email from kanderson.old@hospital.org to kanderson@healthcare.org two weeks ago, but all system-generated reports still show the old address. The profile page shows the new one.\n\nKevin Anderson",
    senderName: "Kevin Anderson",
    senderEmail: "kanderson@healthcare.org",
    status: TicketStatus.inProgress,
    category: "Account",
    daysAgo: 12,
    assignedToId: SUBROTO,
  },
  {
    subject: "Need to merge two separate accounts",
    body: "We accidentally created two accounts for our company — one under jbrown@finance.com and another under jessica.brown@finance.com. We'd like to merge them into one with all data preserved.\n\nJessica Brown",
    senderName: "Jessica Brown",
    senderEmail: "jbrown@finance.com",
    status: TicketStatus.open,
    category: "Account",
    daysAgo: 5,
    assignedToId: null,
  },
  {
    subject: "Audit log missing entries for last week",
    body: "Our security audit requires a complete audit trail. Entries from April 22–28 are absent from the audit log export. The entries exist in the UI but do not appear in the CSV export or API response.\n\nLisa Chen",
    senderName: "Lisa Chen",
    senderEmail: "lchen@enterprise.co",
    status: TicketStatus.inProgress,
    category: "Account",
    daysAgo: 10,
    assignedToId: SUBROTO,
  },
  {
    subject: "Cannot configure sub-accounts for departments",
    body: "Our plan description says 'multi-department support' is included but I cannot find where to create sub-accounts. We need separate ticket queues and billing for Engineering, Sales, and Support.\n\nDaniel Scott",
    senderName: "Daniel Scott",
    senderEmail: "dscott@realestate.com",
    status: TicketStatus.open,
    category: "Account",
    daysAgo: 6,
    assignedToId: null,
  },
  {
    subject: "Username accepted with restricted character",
    body: "A user on our team set their username to 'chris@work' (with an @ symbol) which your signup form accepted. This is now causing issues in some exported reports. Can you sanitise the username?\n\nChris Nguyen",
    senderName: "Chris Nguyen",
    senderEmail: "chris.n@agency.io",
    status: TicketStatus.closed,
    category: "Account",
    daysAgo: 120,
    assignedToId: GOUTOM,
  },
  {
    subject: "Invited user receives invitation email in wrong language",
    body: "When I invite a new team member whose browser is set to Spanish, the invitation email still arrives in English. Our account language is set to Spanish. Is there a per-user language override?\n\nRachel Green",
    senderName: "Rachel Green",
    senderEmail: "rgreen@media.co",
    status: TicketStatus.open,
    category: "Account",
    daysAgo: 4,
    assignedToId: null,
  },
  {
    subject: "Account timezone resets to UTC after every login",
    body: "I set my timezone to America/Chicago in profile settings and it shows correctly until I log out. On next login it reverts to UTC, causing all timestamps to display incorrectly.\n\nThomas Wright",
    senderName: "Thomas Wright",
    senderEmail: "t.wright@logistics.net",
    status: TicketStatus.closed,
    category: "Account",
    daysAgo: 95,
    assignedToId: GOUTOM,
  },

  // ── Shipping (8) ─────────────────────────────────────────────────────────
  {
    subject: "Order #77341 stuck in 'Processing' for 5 days",
    body: "My order placed on April 24th has been showing 'Processing' for 5 days. The estimated dispatch was 1–2 business days. I need this hardware before our office move on May 8th. Please advise.\n\nAmanda Foster",
    senderName: "Amanda Foster",
    senderEmail: "afoster@retail.com",
    status: TicketStatus.inProgress,
    category: "Shipping",
    daysAgo: 6,
    assignedToId: SUBROTO,
  },
  {
    subject: "Shipping address not editable after order placed",
    body: "I made a typo in the flat number (14A instead of 41A) right after placing the order. The 'Edit address' button is greyed out. The order hasn't shipped yet — please update before dispatch.\n\nMaria Lopez",
    senderName: "Maria Lopez",
    senderEmail: "mlopez@education.edu",
    status: TicketStatus.open,
    category: "Shipping",
    daysAgo: 2,
    assignedToId: null,
  },
  {
    subject: "Tracking number link goes to wrong carrier site",
    body: "Order #65190 shows a DHL tracking number but the link goes to FedEx's website which says the number is invalid. The package was actually shipped with DHL — could you fix the tracking link?\n\nRobert Kim",
    senderName: "Robert Kim",
    senderEmail: "r.kim@globex.net",
    status: TicketStatus.closed,
    category: "Shipping",
    daysAgo: 140,
    assignedToId: GOUTOM,
  },
  {
    subject: "Express delivery not available for my postcode",
    body: "Your checkout shows 'Express 1-day delivery' as an option but when I enter postcode SW1A 1AA (central London) it disappears and only Standard is offered. Your FAQ says express covers all UK postcodes.\n\nMichael Torres",
    senderName: "Michael Torres",
    senderEmail: "mtorres@consulting.biz",
    status: TicketStatus.open,
    category: "Shipping",
    daysAgo: 3,
    assignedToId: null,
  },
  {
    subject: "Received wrong item in order #81209",
    body: "I ordered a 256GB USB-C drive (SKU: USB-256-C) but received a 64GB USB-A drive (SKU: USB-064-A). Please arrange collection and send the correct item. I need it urgently for a client demo.\n\nSarah Mitchell",
    senderName: "Sarah Mitchell",
    senderEmail: "sarah.m@techcorp.io",
    status: TicketStatus.inProgress,
    category: "Shipping",
    daysAgo: 5,
    assignedToId: SUBROTO,
  },
  {
    subject: "Package marked as delivered but not received",
    body: "The tracking for order #88401 shows 'Delivered' at 14:23 today but neither I nor my building reception have the package. No card was left. Could you raise a carrier investigation?\n\nJames Carter",
    senderName: "James Carter",
    senderEmail: "james.carter@acme.com",
    status: TicketStatus.open,
    category: "Shipping",
    daysAgo: 1,
    assignedToId: null,
  },
  {
    subject: "International shipping cost shown incorrectly at checkout",
    body: "Shipping to Germany shows $8 at checkout but we are charged $42 on the invoice. This has happened on our last 3 orders. We feel misled by the checkout estimate.\n\nEmily Watson",
    senderName: "Emily Watson",
    senderEmail: "ewatson@startupxyz.com",
    status: TicketStatus.inProgress,
    category: "Shipping",
    daysAgo: 11,
    assignedToId: SUBROTO,
  },
  {
    subject: "Need to reroute shipment to new office address",
    body: "We moved offices last month. Order #90123 is in transit — can you contact DHL to reroute it to 42 Enterprise Way, Manchester, M1 2AB? The original address is no longer staffed.\n\nKevin Anderson",
    senderName: "Kevin Anderson",
    senderEmail: "kanderson@healthcare.org",
    status: TicketStatus.closed,
    category: "Shipping",
    daysAgo: 160,
    assignedToId: GOUTOM,
  },

  // ── Product (10) ─────────────────────────────────────────────────────────
  {
    subject: "Dark mode toggle not persisting between sessions",
    body: "I enable dark mode, use the app, then close the browser. Next time I open it, it's back to light mode. I have cookies enabled and I'm logged in with a persistent session.\n\nChris Nguyen",
    senderName: "Chris Nguyen",
    senderEmail: "chris.n@agency.io",
    status: TicketStatus.open,
    category: "Product",
    daysAgo: 2,
    assignedToId: null,
  },
  {
    subject: "Column widths reset to default after page reload",
    body: "I drag the columns to my preferred widths but any time I refresh the page they snap back to the defaults. Column order persists correctly — it's only the widths that reset.\n\nDavid Park",
    senderName: "David Park",
    senderEmail: "dpark@solutions.org",
    status: TicketStatus.inProgress,
    category: "Product",
    daysAgo: 7,
    assignedToId: SUBROTO,
  },
  {
    subject: "Feature request: bulk assign tickets to an agent",
    body: "We handle 200+ tickets a day and need to bulk-assign them to agents during morning triage. Currently we have to open each ticket individually. This would save significant time for our team of 12.\n\nLisa Chen",
    senderName: "Lisa Chen",
    senderEmail: "lchen@enterprise.co",
    status: TicketStatus.open,
    category: "Product",
    daysAgo: 10,
    assignedToId: null,
  },
  {
    subject: "Keyboard shortcut Ctrl+K conflicts with browser",
    body: "Your in-app search shortcut Ctrl+K also opens the browser's address bar in Chrome. Could you change it to Ctrl+Shift+F or make it configurable? This interrupts workflow constantly.\n\nSarah Mitchell",
    senderName: "Sarah Mitchell",
    senderEmail: "sarah.m@techcorp.io",
    status: TicketStatus.closed,
    category: "Product",
    daysAgo: 55,
    assignedToId: GOUTOM,
  },
  {
    subject: "Comment editor loses formatting on paste from Word",
    body: "When pasting rich text from Microsoft Word into the comment editor all formatting (bold, bullets, headings) is stripped. Our agents write structured responses in Word before pasting. Please preserve at least basic formatting.\n\nJessica Brown",
    senderName: "Jessica Brown",
    senderEmail: "jbrown@finance.com",
    status: TicketStatus.open,
    category: "Product",
    daysAgo: 3,
    assignedToId: null,
  },
  {
    subject: "Filter presets not saved to user profile",
    body: "I create filter presets (e.g. 'My open tickets') but they disappear when I log out and back in. They seem to be stored in localStorage rather than on the server. Please persist them to the user account.\n\nAmanda Foster",
    senderName: "Amanda Foster",
    senderEmail: "afoster@retail.com",
    status: TicketStatus.inProgress,
    category: "Product",
    daysAgo: 14,
    assignedToId: SUBROTO,
  },
  {
    subject: "Feature request: scheduled report delivery by email",
    body: "We'd love the ability to schedule weekly or monthly reports to be emailed automatically to our management team. Manual exports every Monday morning is error-prone and easy to forget.\n\nKevin Anderson",
    senderName: "Kevin Anderson",
    senderEmail: "kanderson@healthcare.org",
    status: TicketStatus.open,
    category: "Product",
    daysAgo: 8,
    assignedToId: null,
  },
  {
    subject: "Emoji picker not appearing on mobile browser",
    body: "The emoji button in the comment toolbar doesn't open the picker on Safari iOS. Tapping it does nothing. The native iOS emoji keyboard doesn't appear either. This is on an iPhone 15, iOS 17.4.\n\nRachel Green",
    senderName: "Rachel Green",
    senderEmail: "rgreen@media.co",
    status: TicketStatus.closed,
    category: "Product",
    daysAgo: 170,
    assignedToId: GOUTOM,
  },
  {
    subject: "Table pagination resets when switching between tabs",
    body: "If I'm on page 4 of the ticket list, switch to the Settings tab, then come back to Tickets, it resets to page 1. Browser back/forward navigation also causes this. Please maintain state.\n\nJames Carter",
    senderName: "James Carter",
    senderEmail: "james.carter@acme.com",
    status: TicketStatus.inProgress,
    category: "Product",
    daysAgo: 6,
    assignedToId: SUBROTO,
  },
  {
    subject: "Feature request: ticket merge functionality",
    body: "When a customer emails from two different addresses about the same issue we end up with duplicate tickets. A merge feature that combines threads and closes the duplicate would be very helpful.\n\nMichael Torres",
    senderName: "Michael Torres",
    senderEmail: "mtorres@consulting.biz",
    status: TicketStatus.open,
    category: "Product",
    daysAgo: 4,
    assignedToId: null,
  },

  // ── Security (8) ─────────────────────────────────────────────────────────
  {
    subject: "Suspicious login from Russia – possible account compromise",
    body: "I received a login notification from Moscow, Russia at 03:14 UTC. I am based in Singapore. I have changed my password but want confirmation that no data was accessed or exported during that session.\n\nLisa Chen",
    senderName: "Lisa Chen",
    senderEmail: "lchen@enterprise.co",
    status: TicketStatus.inProgress,
    category: "Security",
    daysAgo: 4,
    assignedToId: SUBROTO,
  },
  {
    subject: "Phishing email impersonating your support team",
    body: "A member of our staff received an email from 'support@helpdesk-secure.com' asking them to click a link and verify their credentials. The email uses your branding. I am forwarding it separately.\n\nEmily Watson",
    senderName: "Emily Watson",
    senderEmail: "ewatson@startupxyz.com",
    status: TicketStatus.open,
    category: "Security",
    daysAgo: 1,
    assignedToId: null,
  },
  {
    subject: "API key accidentally exposed in public GitHub repo",
    body: "We pushed a commit with our API key in a config file to a public GitHub repository. We have already revoked and regenerated the key. Can you confirm no unusual activity occurred on our account in the last 6 hours?\n\nDaniel Scott",
    senderName: "Daniel Scott",
    senderEmail: "dscott@realestate.com",
    status: TicketStatus.inProgress,
    category: "Security",
    daysAgo: 3,
    assignedToId: SUBROTO,
  },
  {
    subject: "GDPR data export request – full data dump required",
    body: "Under GDPR Article 20 I am requesting a full export of all personal data held for my account (jbrown@finance.com). Please provide this within the statutory 30-day window.\n\nJessica Brown",
    senderName: "Jessica Brown",
    senderEmail: "jbrown@finance.com",
    status: TicketStatus.closed,
    category: "Security",
    daysAgo: 145,
    assignedToId: GOUTOM,
  },
  {
    subject: "Unrecognised login activity on account",
    body: "My account's recent activity shows 12 logins from IP 185.220.101.x over the past 3 days. I have only logged in twice this week from my home IP. Please investigate and advise if I should be concerned.\n\nRobert Kim",
    senderName: "Robert Kim",
    senderEmail: "r.kim@globex.net",
    status: TicketStatus.open,
    category: "Security",
    daysAgo: 2,
    assignedToId: null,
  },
  {
    subject: "Request to enable IP allowlist for enterprise account",
    body: "Our compliance team requires that only requests from our office IP ranges (203.0.113.0/24 and 198.51.100.0/24) can access the API. Please enable IP allowlisting and confirm the process.\n\nKevin Anderson",
    senderName: "Kevin Anderson",
    senderEmail: "kanderson@healthcare.org",
    status: TicketStatus.inProgress,
    category: "Security",
    daysAgo: 9,
    assignedToId: SUBROTO,
  },
  {
    subject: "Agent can view another agent's private notes",
    body: "We discovered that Agent B can view Agent A's private internal notes on tickets they are not assigned to. Private notes should only be visible to the note author and admins. This is a potential data breach.\n\nThomas Wright",
    senderName: "Thomas Wright",
    senderEmail: "t.wright@logistics.net",
    status: TicketStatus.open,
    category: "Security",
    daysAgo: 1,
    assignedToId: null,
  },
  {
    subject: "SOC 2 Type II compliance report needed for procurement",
    body: "Our procurement team requires your latest SOC 2 Type II audit report before we can sign the enterprise contract. Could you share it under NDA? We can provide a signed NDA within 24 hours.\n\nMaria Lopez",
    senderName: "Maria Lopez",
    senderEmail: "mlopez@education.edu",
    status: TicketStatus.closed,
    category: "Security",
    daysAgo: 100,
    assignedToId: GOUTOM,
  },

  // ── Integration (8) ───────────────────────────────────────────────────────
  {
    subject: "Slack integration stopped posting notifications",
    body: "Our Slack integration was working until April 27th. Since then no ticket notifications appear in #support-alerts. The integration status page shows 'Connected' and no errors. I have reconnected it twice.\n\nSarah Mitchell",
    senderName: "Sarah Mitchell",
    senderEmail: "sarah.m@techcorp.io",
    status: TicketStatus.inProgress,
    category: "Integration",
    daysAgo: 5,
    assignedToId: SUBROTO,
  },
  {
    subject: "Zapier webhook returning 401 Unauthorized",
    body: "Our Zapier workflow calls POST /api/webhooks/inbound with a Bearer token. It worked last week but now returns 401. The token is the same and hasn't been rotated. Has something changed with auth?\n\nDavid Park",
    senderName: "David Park",
    senderEmail: "dpark@solutions.org",
    status: TicketStatus.open,
    category: "Integration",
    daysAgo: 2,
    assignedToId: null,
  },
  {
    subject: "Salesforce sync creating duplicate contact records",
    body: "The Salesforce integration is creating a new Contact record on every ticket update rather than updating the existing one. We now have ~300 duplicate contacts. Please advise on the dedup logic.\n\nJames Carter",
    senderName: "James Carter",
    senderEmail: "james.carter@acme.com",
    status: TicketStatus.inProgress,
    category: "Integration",
    daysAgo: 10,
    assignedToId: SUBROTO,
  },
  {
    subject: "Jira integration not creating sub-tasks correctly",
    body: "When a ticket is escalated it should create a Jira issue with sub-tasks for each checklist item. The parent issue is created correctly but sub-tasks are missing. Jira version 9.12.\n\nLisa Chen",
    senderName: "Lisa Chen",
    senderEmail: "lchen@enterprise.co",
    status: TicketStatus.open,
    category: "Integration",
    daysAgo: 6,
    assignedToId: null,
  },
  {
    subject: "Google Calendar sync off by one hour after DST change",
    body: "Since the EU switched to summer time on March 31st, all calendar events synced from your system are showing one hour late. Our team is missing meetings as a result.\n\nRachel Green",
    senderName: "Rachel Green",
    senderEmail: "rgreen@media.co",
    status: TicketStatus.closed,
    category: "Integration",
    daysAgo: 115,
    assignedToId: GOUTOM,
  },
  {
    subject: "HubSpot field mapping broken after CRM update",
    body: "After HubSpot's April 15th update, the 'Ticket Category' field in your integration is no longer mapping to the correct HubSpot property. It now maps to 'Deal Stage' instead. Please update the field mapper.\n\nEmily Watson",
    senderName: "Emily Watson",
    senderEmail: "ewatson@startupxyz.com",
    status: TicketStatus.inProgress,
    category: "Integration",
    daysAgo: 13,
    assignedToId: SUBROTO,
  },
  {
    subject: "Microsoft Teams webhook URL needs rotating",
    body: "Our Teams webhook URL was accidentally shared in a public channel and needs to be rotated immediately. Can we generate a new incoming webhook URL from our side or does this need to be done in your admin?\n\nKevin Anderson",
    senderName: "Kevin Anderson",
    senderEmail: "kanderson@healthcare.org",
    status: TicketStatus.open,
    category: "Integration",
    daysAgo: 4,
    assignedToId: null,
  },
  {
    subject: "Stripe payment events not triggering automation workflow",
    body: "We set up an automation to tag tickets as 'paid' when a Stripe payment.succeeded event is received. The event arrives in the webhook log but the automation never fires. Other event types work.\n\nAmanda Foster",
    senderName: "Amanda Foster",
    senderEmail: "afoster@retail.com",
    status: TicketStatus.closed,
    category: "Integration",
    daysAgo: 90,
    assignedToId: GOUTOM,
  },

  // ── Performance (7) ───────────────────────────────────────────────────────
  {
    subject: "Reports page takes over 8 seconds to load",
    body: "The Analytics > Reports page takes 8–12 seconds to render on a 200 Mbps connection. The browser DevTools show a single XHR request to /api/reports/summary that alone takes 7.8 seconds.\n\nJessica Brown",
    senderName: "Jessica Brown",
    senderEmail: "jbrown@finance.com",
    status: TicketStatus.open,
    category: "Performance",
    daysAgo: 3,
    assignedToId: null,
  },
  {
    subject: "Full-text search takes 15+ seconds for large accounts",
    body: "Our account has ~50,000 tickets. Searching for a keyword takes 15–20 seconds and sometimes times out. Smaller accounts on the same plan report instant results. Looks like a missing index.\n\nMichael Torres",
    senderName: "Michael Torres",
    senderEmail: "mtorres@consulting.biz",
    status: TicketStatus.inProgress,
    category: "Performance",
    daysAgo: 8,
    assignedToId: SUBROTO,
  },
  {
    subject: "Memory leak causing browser tab to crash after 2 hours",
    body: "After approximately 2 hours of use the browser tab's memory usage climbs to 2+ GB and Chrome kills it. This happens consistently on the Tickets page with the WebSocket connection open. Chrome 124, 16 GB RAM.\n\nDaniel Scott",
    senderName: "Daniel Scott",
    senderEmail: "dscott@realestate.com",
    status: TicketStatus.open,
    category: "Performance",
    daysAgo: 2,
    assignedToId: null,
  },
  {
    subject: "File upload throttled to under 1 Mbps",
    body: "Uploading attachments is limited to around 800 Kbps regardless of our internet speed. A 10 MB file takes over 2 minutes. Our ISP shows 500 Mbps to other services at the same time.\n\nChris Nguyen",
    senderName: "Chris Nguyen",
    senderEmail: "chris.n@agency.io",
    status: TicketStatus.closed,
    category: "Performance",
    daysAgo: 75,
    assignedToId: GOUTOM,
  },
  {
    subject: "Dashboard CPU spikes to 100% with many widgets",
    body: "When I have 6+ widgets on the dashboard the browser CPU pegs at 100% and the page becomes unresponsive. With 3 or fewer widgets it's fine. Profiler shows excessive re-renders every second.\n\nThomas Wright",
    senderName: "Thomas Wright",
    senderEmail: "t.wright@logistics.net",
    status: TicketStatus.inProgress,
    category: "Performance",
    daysAgo: 12,
    assignedToId: SUBROTO,
  },
  {
    subject: "Infinite scroll loads duplicate records on fast scroll",
    body: "Scrolling quickly through the ticket list causes the same batch of 20 records to be appended multiple times. Slowing down prevents it. Looks like a debounce issue on the scroll event.\n\nRachel Green",
    senderName: "Rachel Green",
    senderEmail: "rgreen@media.co",
    status: TicketStatus.open,
    category: "Performance",
    daysAgo: 5,
    assignedToId: null,
  },
  {
    subject: "Team overview page causes database query timeout",
    body: "The Team > Overview page reliably returns a 504 every Monday morning when traffic is highest. It works at other times. We suspect an unoptimised aggregation query with no cache.\n\nJames Carter",
    senderName: "James Carter",
    senderEmail: "james.carter@acme.com",
    status: TicketStatus.inProgress,
    category: "Performance",
    daysAgo: 7,
    assignedToId: SUBROTO,
  },

  // ── General (4) ──────────────────────────────────────────────────────────
  {
    subject: "Account reactivation after 6-month inactivity",
    body: "My account was auto-suspended after 6 months of inactivity. I'd like to reactivate it and resume from where I left off. Please advise on any data retention limitations.\n\nMaria Lopez",
    senderName: "Maria Lopez",
    senderEmail: "mlopez@education.edu",
    status: TicketStatus.closed,
    category: "General",
    daysAgo: 150,
    assignedToId: GOUTOM,
  },
  {
    subject: "Guidance on which plan suits a 50-person team",
    body: "We are evaluating your product for a 50-person support team. We need SSO, audit logs, and custom roles. Could a sales engineer walk us through the plan options and limits?\n\nRobert Kim",
    senderName: "Robert Kim",
    senderEmail: "r.kim@globex.net",
    status: TicketStatus.closed,
    category: "General",
    daysAgo: 165,
    assignedToId: GOUTOM,
  },
  {
    subject: "Onboarding consultation for new enterprise account",
    body: "We just signed the enterprise contract and want to schedule an onboarding session with your team. We have 80 agents across 4 time zones and need help with role configuration and automations.\n\nEmily Watson",
    senderName: "Emily Watson",
    senderEmail: "ewatson@startupxyz.com",
    status: TicketStatus.inProgress,
    category: "General",
    daysAgo: 5,
    assignedToId: SUBROTO,
  },
  {
    subject: "Requesting product documentation in Portuguese",
    body: "We are rolling out the platform to our Brazil office (40 users). Is the user documentation available in Brazilian Portuguese? If not, is there a community translation project we could contribute to?\n\nKevin Anderson",
    senderName: "Kevin Anderson",
    senderEmail: "kanderson@healthcare.org",
    status: TicketStatus.open,
    category: "General",
    daysAgo: 7,
    assignedToId: null,
  },
];

async function main() {
  const data = tickets.map((t, i) => ({
    subject: t.subject,
    body: t.body,
    senderName: t.senderName,
    senderEmail: t.senderEmail,
    status: t.status,
    category: t.category,
    messageId: `seed-${String(i + 1).padStart(3, "0")}@helpdesk.example.com`,
    assignedToId: t.assignedToId,
    createdAt: daysAgo(t.daysAgo),
    updatedAt: daysAgo(Math.max(0, t.daysAgo - 1)),
  }));

  const result = await db.ticket.createMany({ data, skipDuplicates: true });
  console.log(`Created ${result.count} tickets (${tickets.length - result.count} skipped as duplicates)`);
}

main()
  .catch((err) => {
    console.error(err);
    process.exitCode = 1;
  })
  .finally(async () => {
    await db.$disconnect();
  });
