import "dotenv/config";
import { db } from "./db";
import { TicketStatus } from "./generated/prisma/client";

const SUBROTO = "72798743-eb6c-43f4-8529-c361c69b7644";
const GOUTOM = "320865d3-ffc5-4c24-a894-7d4b99dbd2ca";

const daysAgo = (n: number): Date => {
  const d = new Date();
  d.setDate(d.getDate() - n);
  return d;
};

type RawTicket = {
  subject: string;
  body: string;
  senderName: string;
  senderEmail: string;
  status: TicketStatus;
  category: string;
  daysAgo: number;
  assignedToId: string | null;
};

const tickets: RawTicket[] = [
  // ── General Question (35) ─────────────────────────────────────────────────
  {
    subject: "When does the next cohort start?",
    body: "Hi,\n\nI am interested in enrolling but I missed the current intake. Could you let me know when the next cohort begins and whether early registration is open?\n\nThanks,\nEmma Johnson",
    senderName: "Emma Johnson",
    senderEmail: "emma.j@student.edu",
    status: TicketStatus.open,
    category: "General Question",
    daysAgo: 2,
    assignedToId: null,
  },
  {
    subject: "Can I access course materials after completing the course?",
    body: "Hello,\n\nI completed the Web Development Bootcamp last week. Will I still be able to access the video lessons and downloadable resources, or does access expire at completion?\n\nLiam Williams",
    senderName: "Liam Williams",
    senderEmail: "l.williams@college.net",
    status: TicketStatus.closed,
    category: "General Question",
    daysAgo: 55,
    assignedToId: GOUTOM,
  },
  {
    subject: "What is the difference between the Basic and Pro plan?",
    body: "Hi there,\n\nI am trying to decide between the Basic and Pro plans. The pricing page lists features but doesn't explain the practical difference. Can an agent walk me through the key benefits of upgrading?\n\nOlivia Brown",
    senderName: "Olivia Brown",
    senderEmail: "olivia.b@university.edu",
    status: TicketStatus.closed,
    category: "General Question",
    daysAgo: 70,
    assignedToId: GOUTOM,
  },
  {
    subject: "How do I download my certificate of completion?",
    body: "Hello support,\n\nI finished the Data Science Fundamentals course three days ago but my dashboard only shows 'Certificate Pending'. How long does it take and how do I download it once it's ready?\n\nNoah Davis",
    senderName: "Noah Davis",
    senderEmail: "n.davis@student.edu",
    status: TicketStatus.inProgress,
    category: "General Question",
    daysAgo: 6,
    assignedToId: SUBROTO,
  },
  {
    subject: "Is there a mobile app for the learning platform?",
    body: "Hi,\n\nI do most of my studying on the go. Do you have an iOS or Android app? I could not find it on the App Store. If not, is a mobile app on the roadmap?\n\nAva Martinez",
    senderName: "Ava Martinez",
    senderEmail: "ava.m@college.net",
    status: TicketStatus.open,
    category: "General Question",
    daysAgo: 3,
    assignedToId: null,
  },
  {
    subject: "How many hours per week does the course require?",
    body: "Hello,\n\nI work full-time and want to make sure I can keep up. Roughly how many hours per week should I budget for the UX Design course? Is it self-paced or are there mandatory live sessions?\n\nIsabella Garcia",
    senderName: "Isabella Garcia",
    senderEmail: "i.garcia@uni.edu",
    status: TicketStatus.closed,
    category: "General Question",
    daysAgo: 90,
    assignedToId: GOUTOM,
  },
  {
    subject: "Can I switch to a different course midway through?",
    body: "Hi support,\n\nI enrolled in the Python course but I think the JavaScript course is more relevant for my job. Is it possible to switch courses without losing my subscription time or paying again?\n\nSophia Rodriguez",
    senderName: "Sophia Rodriguez",
    senderEmail: "s.rodriguez@student.edu",
    status: TicketStatus.open,
    category: "General Question",
    daysAgo: 4,
    assignedToId: null,
  },
  {
    subject: "Do you offer group or corporate discounts?",
    body: "Hello,\n\nI manage a team of 12 developers and we'd like to enrol them all. Do you offer bulk pricing or a corporate plan? If so, please send the details and I'll forward them to our HR team.\n\nMason Wilson",
    senderName: "Mason Wilson",
    senderEmail: "m.wilson@college.net",
    status: TicketStatus.inProgress,
    category: "General Question",
    daysAgo: 9,
    assignedToId: SUBROTO,
  },
  {
    subject: "What language is the course taught in?",
    body: "Hi,\n\nI noticed the platform has content in multiple languages. Is the Machine Learning course available in Spanish, or only in English? My team includes non-English speakers.\n\nMia Anderson",
    senderName: "Mia Anderson",
    senderEmail: "mia.a@university.edu",
    status: TicketStatus.closed,
    category: "General Question",
    daysAgo: 110,
    assignedToId: GOUTOM,
  },
  {
    subject: "Is the course accredited by any institution?",
    body: "Hello,\n\nI need to know if the Project Management course is accredited before I enrol. My employer requires accredited training for reimbursement. Could you provide the accrediting body details?\n\nLucas Thomas",
    senderName: "Lucas Thomas",
    senderEmail: "l.thomas@student.edu",
    status: TicketStatus.open,
    category: "General Question",
    daysAgo: 5,
    assignedToId: null,
  },
  {
    subject: "How long do I have access to course content?",
    body: "Hi,\n\nI want to confirm whether access is lifetime or time-limited. The FAQ says 'full access' but doesn't specify the duration. I'd like to revisit the material a year after completing it.\n\nCharlotte Jackson",
    senderName: "Charlotte Jackson",
    senderEmail: "c.jackson@college.net",
    status: TicketStatus.inProgress,
    category: "General Question",
    daysAgo: 11,
    assignedToId: SUBROTO,
  },
  {
    subject: "Can I pause my subscription and resume it later?",
    body: "Hello,\n\nI have a family commitment coming up next month and won't be able to study for about 6 weeks. Is it possible to pause my subscription so I don't lose paid time?\n\nElijah White",
    senderName: "Elijah White",
    senderEmail: "e.white@uni.edu",
    status: TicketStatus.open,
    category: "General Question",
    daysAgo: 2,
    assignedToId: null,
  },
  {
    subject: "Are there live sessions or is it all pre-recorded?",
    body: "Hi support,\n\nBefore purchasing I'd like to know whether the Cybersecurity course includes live instructor-led sessions or is purely self-paced video content. Are there office hours I can attend?\n\nAmelia Harris",
    senderName: "Amelia Harris",
    senderEmail: "a.harris@student.edu",
    status: TicketStatus.closed,
    category: "General Question",
    daysAgo: 80,
    assignedToId: GOUTOM,
  },
  {
    subject: "What prerequisites are needed for the advanced AI course?",
    body: "Hello,\n\nI completed the Intro to AI course and want to move to the Advanced track. Are there specific prerequisites (e.g. calculus, linear algebra, Python) I should review before enrolling?\n\nOliver Martin",
    senderName: "Oliver Martin",
    senderEmail: "o.martin@college.net",
    status: TicketStatus.open,
    category: "General Question",
    daysAgo: 3,
    assignedToId: null,
  },
  {
    subject: "Is there a student community or discussion forum?",
    body: "Hi,\n\nI learn better when I can discuss topics with peers. Does the platform have a community forum or Slack workspace where enrolled students can interact and ask questions?\n\nHarper Thompson",
    senderName: "Harper Thompson",
    senderEmail: "h.thompson@university.edu",
    status: TicketStatus.inProgress,
    category: "General Question",
    daysAgo: 7,
    assignedToId: SUBROTO,
  },
  {
    subject: "How do I contact my course instructor directly?",
    body: "Hello,\n\nI have a specific question about a coding exercise in module 4 that I don't think belongs in the public forum. Is there a way to send a private message to the instructor?\n\nBenjamin Garcia",
    senderName: "Benjamin Garcia",
    senderEmail: "b.garcia@student.edu",
    status: TicketStatus.open,
    category: "General Question",
    daysAgo: 1,
    assignedToId: null,
  },
  {
    subject: "Can I retake the final exam if I fail?",
    body: "Hi,\n\nI failed the final assessment for the Cloud Computing course by 3 marks. The passing grade is 70% and I scored 67%. Am I allowed to retake it? If so, is there a waiting period?\n\nEvelyn Lee",
    senderName: "Evelyn Lee",
    senderEmail: "e.lee@college.net",
    status: TicketStatus.closed,
    category: "General Question",
    daysAgo: 45,
    assignedToId: GOUTOM,
  },
  {
    subject: "Are assignments peer-reviewed or instructor-graded?",
    body: "Hello,\n\nI noticed the course has weekly assignments. Could you clarify whether these are graded by the instructor, by peers, or by an automated system? This affects how I plan my schedule.\n\nAiden Clark",
    senderName: "Aiden Clark",
    senderEmail: "a.clark@uni.edu",
    status: TicketStatus.open,
    category: "General Question",
    daysAgo: 4,
    assignedToId: null,
  },
  {
    subject: "What happens if I miss a live session?",
    body: "Hi support,\n\nI am in a different time zone and may occasionally miss the live sessions. Are recordings made available afterwards? How long after the session are they posted?\n\nAbigail Lewis",
    senderName: "Abigail Lewis",
    senderEmail: "ab.lewis@student.edu",
    status: TicketStatus.inProgress,
    category: "General Question",
    daysAgo: 8,
    assignedToId: SUBROTO,
  },
  {
    subject: "Can I get a tax receipt for my course purchase?",
    body: "Hello,\n\nI need a VAT receipt for the course I purchased last week for my self-assessment tax return. Could you send one to logan.hall@college.net? The order number is ORD-20241108.\n\nLogan Hall",
    senderName: "Logan Hall",
    senderEmail: "l.hall@college.net",
    status: TicketStatus.open,
    category: "General Question",
    daysAgo: 3,
    assignedToId: null,
  },
  {
    subject: "Is there a student discount available?",
    body: "Hi,\n\nI am a full-time university student and I noticed some platforms offer student pricing. Do you have a discount for students, and if so, what proof of enrollment do you require?\n\nEmma Johnson",
    senderName: "Emma Johnson",
    senderEmail: "emma.j@student.edu",
    status: TicketStatus.closed,
    category: "General Question",
    daysAgo: 60,
    assignedToId: GOUTOM,
  },
  {
    subject: "How do I update my profile and billing information?",
    body: "Hello,\n\nI recently moved and need to update my address and preferred payment method. I found the profile page but the 'Save' button is greyed out after I make changes. Please advise.\n\nLiam Williams",
    senderName: "Liam Williams",
    senderEmail: "l.williams@college.net",
    status: TicketStatus.open,
    category: "General Question",
    daysAgo: 2,
    assignedToId: null,
  },
  {
    subject: "Can I share my account login with a classmate?",
    body: "Hi,\n\nMy classmate and I purchased the same course separately. Is it against the terms to share login credentials? We'd like to save money on a second subscription.\n\nOlivia Brown",
    senderName: "Olivia Brown",
    senderEmail: "olivia.b@university.edu",
    status: TicketStatus.closed,
    category: "General Question",
    daysAgo: 95,
    assignedToId: GOUTOM,
  },
  {
    subject: "Does the platform have a referral or affiliate program?",
    body: "Hello,\n\nI have recommended the platform to several colleagues and friends. Is there a referral program that rewards me when they sign up? I'd love to share a referral link.\n\nNoah Davis",
    senderName: "Noah Davis",
    senderEmail: "n.davis@student.edu",
    status: TicketStatus.open,
    category: "General Question",
    daysAgo: 5,
    assignedToId: null,
  },
  {
    subject: "Do you offer internship placement after completing the course?",
    body: "Hi support,\n\nI saw a mention of career support on the website. Does the platform help graduates find internships or entry-level jobs? Is there a job board or career services team I can contact?\n\nAva Martinez",
    senderName: "Ava Martinez",
    senderEmail: "ava.m@college.net",
    status: TicketStatus.inProgress,
    category: "General Question",
    daysAgo: 13,
    assignedToId: SUBROTO,
  },
  {
    subject: "Is closed captioning available for all video lessons?",
    body: "Hello,\n\nI am hard of hearing and rely on closed captions. Are auto-generated or human-edited captions available for all video content, including older courses uploaded before 2023?\n\nIsabella Garcia",
    senderName: "Isabella Garcia",
    senderEmail: "i.garcia@uni.edu",
    status: TicketStatus.open,
    category: "General Question",
    daysAgo: 4,
    assignedToId: null,
  },
  {
    subject: "What time zone are the scheduled live classes held in?",
    body: "Hi,\n\nI am based in Sydney (AEDT, UTC+11) and I want to make sure the live class times work for me. Are sessions held in UTC, EST, or another time zone? Can I see the schedule before enrolling?\n\nSophia Rodriguez",
    senderName: "Sophia Rodriguez",
    senderEmail: "s.rodriguez@student.edu",
    status: TicketStatus.open,
    category: "General Question",
    daysAgo: 1,
    assignedToId: null,
  },
  {
    subject: "Can I enrol in multiple courses at the same time?",
    body: "Hello,\n\nI want to study both the Frontend and Backend courses concurrently. Does the platform allow multiple active enrolments, and do I pay separately for each?\n\nMason Wilson",
    senderName: "Mason Wilson",
    senderEmail: "m.wilson@college.net",
    status: TicketStatus.closed,
    category: "General Question",
    daysAgo: 75,
    assignedToId: GOUTOM,
  },
  {
    subject: "How often is the course content updated?",
    body: "Hi,\n\nTechnology moves fast. How frequently is the curriculum updated to reflect current industry standards? For example, is the React course based on React 18 or an older version?\n\nMia Anderson",
    senderName: "Mia Anderson",
    senderEmail: "mia.a@university.edu",
    status: TicketStatus.inProgress,
    category: "General Question",
    daysAgo: 10,
    assignedToId: SUBROTO,
  },
  {
    subject: "Is there a free trial before purchasing a full course?",
    body: "Hello,\n\nI'd like to experience the teaching style and platform quality before committing. Do you offer a free trial, sample lessons, or a money-back guarantee period?\n\nLucas Thomas",
    senderName: "Lucas Thomas",
    senderEmail: "l.thomas@student.edu",
    status: TicketStatus.open,
    category: "General Question",
    daysAgo: 2,
    assignedToId: null,
  },
  {
    subject: "What is the difference between a certificate and a diploma?",
    body: "Hi support,\n\nThe catalogue lists both 'Certificate of Completion' and 'Professional Diploma' programmes. What is the difference in terms of hours, assessment, and recognition by employers?\n\nCharlotte Jackson",
    senderName: "Charlotte Jackson",
    senderEmail: "c.jackson@college.net",
    status: TicketStatus.closed,
    category: "General Question",
    daysAgo: 120,
    assignedToId: GOUTOM,
  },
  {
    subject: "Can I access the platform on a Chromebook?",
    body: "Hello,\n\nI only have a Chromebook available. Will all features of the platform work on Chrome OS, including the interactive coding exercises and live session tools?\n\nElijah White",
    senderName: "Elijah White",
    senderEmail: "e.white@uni.edu",
    status: TicketStatus.open,
    category: "General Question",
    daysAgo: 3,
    assignedToId: null,
  },
  {
    subject: "How are course ratings and reviews moderated?",
    body: "Hi,\n\nI wanted to leave a review for the Data Analytics course but my submission has been pending for 5 days. What is the moderation process and how long does it typically take?\n\nAmelia Harris",
    senderName: "Amelia Harris",
    senderEmail: "a.harris@student.edu",
    status: TicketStatus.inProgress,
    category: "General Question",
    daysAgo: 6,
    assignedToId: SUBROTO,
  },
  {
    subject: "Can I get a letter of recommendation from my instructor?",
    body: "Hello,\n\nI completed the Full Stack Development diploma with a distinction. Is it possible to request a formal letter of recommendation from my instructor for graduate school applications?\n\nOliver Martin",
    senderName: "Oliver Martin",
    senderEmail: "o.martin@college.net",
    status: TicketStatus.open,
    category: "General Question",
    daysAgo: 4,
    assignedToId: null,
  },
  {
    subject: "What is the policy for cancelling a live workshop booking?",
    body: "Hi support,\n\nI booked a live workshop for next Friday but my schedule has changed. What is the cancellation policy and is there a deadline to cancel without losing my payment?\n\nHarper Thompson",
    senderName: "Harper Thompson",
    senderEmail: "h.thompson@university.edu",
    status: TicketStatus.inProgress,
    category: "General Question",
    daysAgo: 8,
    assignedToId: SUBROTO,
  },

  // ── Technical Question (35) ───────────────────────────────────────────────
  {
    subject: "Video lessons will not play in Chrome",
    body: "Hello,\n\nI cannot get any video to play. The player shows a loading spinner indefinitely. I am using Chrome 124 on Windows 11. I have tried disabling all extensions and clearing the cache — same result.\n\nBenjamin Garcia",
    senderName: "Benjamin Garcia",
    senderEmail: "b.garcia@student.edu",
    status: TicketStatus.inProgress,
    category: "Technical Question",
    daysAgo: 2,
    assignedToId: SUBROTO,
  },
  {
    subject: "Cannot access the quiz after watching the lecture",
    body: "Hi,\n\nI completed Module 3 lesson 4 but the 'Take Quiz' button remains greyed out. The lesson is marked as complete in the sidebar. I have tried refreshing and logging out/in.\n\nEvelyn Lee",
    senderName: "Evelyn Lee",
    senderEmail: "e.lee@college.net",
    status: TicketStatus.open,
    category: "Technical Question",
    daysAgo: 3,
    assignedToId: null,
  },
  {
    subject: "Progress bar not updating after completing modules",
    body: "Hello,\n\nI have finished 6 of the 10 modules in the DevOps course but my progress bar still shows 0%. This means I cannot unlock the certificate. Can you reset or manually update my progress?\n\nAiden Clark",
    senderName: "Aiden Clark",
    senderEmail: "a.clark@uni.edu",
    status: TicketStatus.inProgress,
    category: "Technical Question",
    daysAgo: 5,
    assignedToId: SUBROTO,
  },
  {
    subject: "Certificate download link returns a 404 error",
    body: "Hi support,\n\nI received a certificate email with a download link but clicking it gives a 404 Not Found error. I have tried the link on multiple browsers and devices. Certificate ID: CERT-2024-8821.\n\nAbigail Lewis",
    senderName: "Abigail Lewis",
    senderEmail: "ab.lewis@student.edu",
    status: TicketStatus.open,
    category: "Technical Question",
    daysAgo: 1,
    assignedToId: null,
  },
  {
    subject: "Platform keeps logging me out during video playback",
    body: "Hello,\n\nEvery 20–30 minutes while watching a lesson I am automatically logged out and lose my place in the video. I have to log in and manually seek to where I was. This is very frustrating.\n\nLogan Hall",
    senderName: "Logan Hall",
    senderEmail: "l.hall@college.net",
    status: TicketStatus.inProgress,
    category: "Technical Question",
    daysAgo: 7,
    assignedToId: SUBROTO,
  },
  {
    subject: "Audio is out of sync with the video on lesson 5",
    body: "Hi,\n\nIn the SQL Fundamentals course, lesson 5 ('Joins and Subqueries') the audio is approximately 3 seconds behind the video. This makes it very hard to follow. All other lessons are fine.\n\nEmma Johnson",
    senderName: "Emma Johnson",
    senderEmail: "emma.j@student.edu",
    status: TicketStatus.open,
    category: "Technical Question",
    daysAgo: 2,
    assignedToId: null,
  },
  {
    subject: "Submitted assignment but instructor says it was not received",
    body: "Hello,\n\nI submitted my Module 2 assignment on 28 April and the platform shows 'Submitted'. However, my instructor says they have not received it. Can you check the submission logs?\n\nLiam Williams",
    senderName: "Liam Williams",
    senderEmail: "l.williams@college.net",
    status: TicketStatus.inProgress,
    category: "Technical Question",
    daysAgo: 6,
    assignedToId: SUBROTO,
  },
  {
    subject: "In-browser code editor not saving my work",
    body: "Hi,\n\nEvery time I close the coding exercise tab my code is lost. The 'Autosave' indicator shows a green tick but the work is gone on next visit. This has cost me hours of re-writing exercises.\n\nOlivia Brown",
    senderName: "Olivia Brown",
    senderEmail: "olivia.b@university.edu",
    status: TicketStatus.open,
    category: "Technical Question",
    daysAgo: 3,
    assignedToId: null,
  },
  {
    subject: "Live session link gives 'Meeting Expired' error",
    body: "Hello,\n\nThe link in my enrolment email for today's live session gives a 'Meeting Expired' error. The session is scheduled for 3pm–5pm UTC today and I have not missed it. Please send a working link.\n\nNoah Davis",
    senderName: "Noah Davis",
    senderEmail: "n.davis@student.edu",
    status: TicketStatus.inProgress,
    category: "Technical Question",
    daysAgo: 1,
    assignedToId: SUBROTO,
  },
  {
    subject: "Cannot download the course PDF workbook",
    body: "Hi support,\n\nThe 'Download Workbook' button on the Resources page opens a blank tab and nothing downloads. I have tried Chrome, Firefox, and Safari. The file size shown is 4.2 MB.\n\nAva Martinez",
    senderName: "Ava Martinez",
    senderEmail: "ava.m@college.net",
    status: TicketStatus.open,
    category: "Technical Question",
    daysAgo: 2,
    assignedToId: null,
  },
  {
    subject: "Two-factor authentication code not arriving by email",
    body: "Hello,\n\nSince enabling 2FA I have not received a single verification code by email. I have checked my spam folder. Without the code I cannot log in. Please help me regain access.\n\nIsabella Garcia",
    senderName: "Isabella Garcia",
    senderEmail: "i.garcia@uni.edu",
    status: TicketStatus.inProgress,
    category: "Technical Question",
    daysAgo: 4,
    assignedToId: SUBROTO,
  },
  {
    subject: "Platform search returns no results for any keyword",
    body: "Hi,\n\nThe search bar on the course library page returns 'No results found' for every search term including exact course names like 'React' and 'Python Basics'. This started after yesterday's update.\n\nSophia Rodriguez",
    senderName: "Sophia Rodriguez",
    senderEmail: "s.rodriguez@student.edu",
    status: TicketStatus.open,
    category: "Technical Question",
    daysAgo: 1,
    assignedToId: null,
  },
  {
    subject: "Course completion not recorded despite finishing all modules",
    body: "Hello,\n\nI have completed all 12 modules and both assessments of the Agile course. My dashboard still shows 'In Progress' and will not let me claim the certificate. Module completion dates are all showing correctly.\n\nMason Wilson",
    senderName: "Mason Wilson",
    senderEmail: "m.wilson@college.net",
    status: TicketStatus.inProgress,
    category: "Technical Question",
    daysAgo: 8,
    assignedToId: SUBROTO,
  },
  {
    subject: "Payment page freezes when I enter my card details",
    body: "Hi,\n\nI have tried to purchase the Digital Marketing course three times. Each time I enter my card number the page stops responding and I have to close the tab. No charge appears on my bank statement.\n\nMia Anderson",
    senderName: "Mia Anderson",
    senderEmail: "mia.a@university.edu",
    status: TicketStatus.open,
    category: "Technical Question",
    daysAgo: 2,
    assignedToId: null,
  },
  {
    subject: "Email verification link expired before I could use it",
    body: "Hello,\n\nI signed up but the verification email arrived 2 hours after registration and the link had already expired. I have clicked 'Resend' three times but each new email also seems to expire immediately.\n\nLucas Thomas",
    senderName: "Lucas Thomas",
    senderEmail: "l.thomas@student.edu",
    status: TicketStatus.inProgress,
    category: "Technical Question",
    daysAgo: 3,
    assignedToId: SUBROTO,
  },
  {
    subject: "Locked out after resetting my password",
    body: "Hi support,\n\nI reset my password using the email link, set a new password, and was told it was successful. But logging in with the new password gives 'Invalid credentials'. The old password also no longer works.\n\nCharlotte Jackson",
    senderName: "Charlotte Jackson",
    senderEmail: "c.jackson@college.net",
    status: TicketStatus.open,
    category: "Technical Question",
    daysAgo: 1,
    assignedToId: null,
  },
  {
    subject: "Video quality stuck at 360p regardless of internet speed",
    body: "Hello,\n\nAll videos play at 360p only. The quality selector in the player is greyed out with no option to change resolution. My internet speed is 200 Mbps and other streaming services work at 4K.\n\nElijah White",
    senderName: "Elijah White",
    senderEmail: "e.white@uni.edu",
    status: TicketStatus.closed,
    category: "Technical Question",
    daysAgo: 65,
    assignedToId: GOUTOM,
  },
  {
    subject: "Lesson bookmark not saving my position",
    body: "Hi,\n\nWhen I bookmark a lesson the platform says 'Saved' but when I return the next day it opens the lesson from the beginning instead of from the bookmarked timestamp. I have tried two browsers.\n\nAmelia Harris",
    senderName: "Amelia Harris",
    senderEmail: "a.harris@student.edu",
    status: TicketStatus.open,
    category: "Technical Question",
    daysAgo: 3,
    assignedToId: null,
  },
  {
    subject: "Cannot upload my project file – format not accepted",
    body: "Hello,\n\nThe assignment instructions say to upload a .zip file but the upload modal says 'File type not supported'. The file is 8 MB and contains HTML, CSS, and JS files. Can you expand the accepted file types?\n\nOliver Martin",
    senderName: "Oliver Martin",
    senderEmail: "o.martin@college.net",
    status: TicketStatus.inProgress,
    category: "Technical Question",
    daysAgo: 5,
    assignedToId: SUBROTO,
  },
  {
    subject: "Forum posts disappear after refreshing the page",
    body: "Hi,\n\nI posted a question in the course forum and it appeared briefly, but after refreshing the page it is gone. This has happened three times. Other students' posts remain visible.\n\nHarper Thompson",
    senderName: "Harper Thompson",
    senderEmail: "h.thompson@university.edu",
    status: TicketStatus.open,
    category: "Technical Question",
    daysAgo: 2,
    assignedToId: null,
  },
  {
    subject: "Course transcript does not match the video content",
    body: "Hello,\n\nThe downloadable transcript for lesson 8 of the Statistics course appears to be from a different lesson entirely. It references topics not covered in the video. Please correct the transcript.\n\nBenjamin Garcia",
    senderName: "Benjamin Garcia",
    senderEmail: "b.garcia@student.edu",
    status: TicketStatus.closed,
    category: "Technical Question",
    daysAgo: 85,
    assignedToId: GOUTOM,
  },
  {
    subject: "Did not receive a confirmation email after registration",
    body: "Hi support,\n\nI registered 48 hours ago and have not received a confirmation email. My account appears active (I can log in) but I am missing the welcome resources mentioned in the confirmation email.\n\nEvelyn Lee",
    senderName: "Evelyn Lee",
    senderEmail: "e.lee@college.net",
    status: TicketStatus.open,
    category: "Technical Question",
    daysAgo: 2,
    assignedToId: null,
  },
  {
    subject: "Interactive whiteboard not loading in live class",
    body: "Hello,\n\nDuring today's live session the whiteboard tool showed a blank white area with a spinning loader for the entire 2-hour class. All other students reported the same. We missed the hands-on exercise.\n\nAiden Clark",
    senderName: "Aiden Clark",
    senderEmail: "a.clark@uni.edu",
    status: TicketStatus.inProgress,
    category: "Technical Question",
    daysAgo: 4,
    assignedToId: SUBROTO,
  },
  {
    subject: "My saved notes were wiped after updating the app",
    body: "Hi,\n\nAfter updating the iOS app to version 5.2.1 all my in-app notes for the Marketing Analytics course were deleted. I had approximately 40 pages of notes. Is there a backup I can restore from?\n\nAbigail Lewis",
    senderName: "Abigail Lewis",
    senderEmail: "ab.lewis@student.edu",
    status: TicketStatus.open,
    category: "Technical Question",
    daysAgo: 3,
    assignedToId: null,
  },
  {
    subject: "Screen sharing not working during live session",
    body: "Hello,\n\nWhen I try to share my screen during the live coding session the browser asks for permission, I grant it, but nothing is shared and the presenter view stays blank. Chrome 124, macOS Sonoma.\n\nLogan Hall",
    senderName: "Logan Hall",
    senderEmail: "l.hall@college.net",
    status: TicketStatus.closed,
    category: "Technical Question",
    daysAgo: 100,
    assignedToId: GOUTOM,
  },
  {
    subject: "Course content appears blank on Safari for iPad",
    body: "Hi,\n\nOn my iPad Pro (iPadOS 17.4, Safari), the course content area is completely white. The navigation works but no lesson content displays. The same course works on Chrome on my laptop.\n\nEmma Johnson",
    senderName: "Emma Johnson",
    senderEmail: "emma.j@student.edu",
    status: TicketStatus.inProgress,
    category: "Technical Question",
    daysAgo: 6,
    assignedToId: SUBROTO,
  },
  {
    subject: "Submit button disabled on final project submission page",
    body: "Hello,\n\nI have filled in all required fields on the final project submission form but the 'Submit' button remains disabled. There are no visible error messages. The deadline is in 4 hours.\n\nLiam Williams",
    senderName: "Liam Williams",
    senderEmail: "l.williams@college.net",
    status: TicketStatus.open,
    category: "Technical Question",
    daysAgo: 1,
    assignedToId: null,
  },
  {
    subject: "Subtitles not displaying for lessons in Spanish",
    body: "Hi support,\n\nI am taking the Spanish language course and the 'Subtitles' toggle is enabled, but no subtitles appear in any of the lessons. The setting saves correctly but has no effect.\n\nOlivia Brown",
    senderName: "Olivia Brown",
    senderEmail: "olivia.b@university.edu",
    status: TicketStatus.closed,
    category: "Technical Question",
    daysAgo: 90,
    assignedToId: GOUTOM,
  },
  {
    subject: "Dashboard is showing a different course than the one I bought",
    body: "Hello,\n\nI purchased the Advanced Excel course but my dashboard shows the Intro to Excel course. I have the purchase confirmation email. My account may have been assigned the wrong course.\n\nNoah Davis",
    senderName: "Noah Davis",
    senderEmail: "n.davis@student.edu",
    status: TicketStatus.inProgress,
    category: "Technical Question",
    daysAgo: 5,
    assignedToId: SUBROTO,
  },
  {
    subject: "Coupon code not applying at checkout",
    body: "Hi,\n\nI received a 20% off coupon code (SAVE20APR) in a newsletter email but when I enter it at checkout it says 'Invalid or expired code'. The email says the code is valid until 31 May.\n\nAva Martinez",
    senderName: "Ava Martinez",
    senderEmail: "ava.m@college.net",
    status: TicketStatus.open,
    category: "Technical Question",
    daysAgo: 2,
    assignedToId: null,
  },
  {
    subject: "Platform is very slow and unresponsive after the latest update",
    body: "Hello,\n\nSince the update deployed on 29 April the platform takes 10–15 seconds to load any page. Navigating between lessons is especially slow. This is affecting the entire class of 30 students.\n\nIsabella Garcia",
    senderName: "Isabella Garcia",
    senderEmail: "i.garcia@uni.edu",
    status: TicketStatus.inProgress,
    category: "Technical Question",
    daysAgo: 4,
    assignedToId: SUBROTO,
  },
  {
    subject: "Getting a 403 Forbidden error when accessing my enrolled course",
    body: "Hi,\n\nI paid for the iOS Development course last week and it was accessible until this morning. Now clicking on it gives a 403 error. My subscription is active and payment was successful. Order: ORD-20240425.\n\nSophia Rodriguez",
    senderName: "Sophia Rodriguez",
    senderEmail: "s.rodriguez@student.edu",
    status: TicketStatus.open,
    category: "Technical Question",
    daysAgo: 1,
    assignedToId: null,
  },
  {
    subject: "Google Calendar integration not syncing class schedule",
    body: "Hello,\n\nI connected my Google Calendar in account settings and authorised the integration. However, my live class schedule is not appearing in Google Calendar. The connection status shows 'Active'.\n\nMason Wilson",
    senderName: "Mason Wilson",
    senderEmail: "m.wilson@college.net",
    status: TicketStatus.inProgress,
    category: "Technical Question",
    daysAgo: 9,
    assignedToId: SUBROTO,
  },
  {
    subject: "Quiz score not saved after completing the assessment",
    body: "Hi support,\n\nI completed the end-of-module quiz for Module 6, reviewed my answers, and clicked 'Submit'. The results screen showed my score as 82%. But when I checked my grade book the quiz shows as 'Not Attempted'.\n\nMia Anderson",
    senderName: "Mia Anderson",
    senderEmail: "mia.a@university.edu",
    status: TicketStatus.open,
    category: "Technical Question",
    daysAgo: 3,
    assignedToId: null,
  },

  // ── Refund Request (30) ───────────────────────────────────────────────────
  {
    subject: "Refund request – accidentally purchased the wrong course",
    body: "Hello,\n\nI meant to purchase the Advanced Python course but accidentally clicked and purchased the Beginner Python course. I only noticed after the payment was processed 10 minutes ago. I have not accessed any content. Order: ORD-20240501.\n\nLucas Thomas",
    senderName: "Lucas Thomas",
    senderEmail: "l.thomas@student.edu",
    status: TicketStatus.inProgress,
    category: "Refund Request",
    daysAgo: 1,
    assignedToId: SUBROTO,
  },
  {
    subject: "Course content does not match the description – refund requested",
    body: "Hi,\n\nThe listing for the Blockchain Development course described 'hands-on smart contract development'. The actual content is 90% theory slides with no coding exercises. I would like a full refund.\n\nCharlotte Jackson",
    senderName: "Charlotte Jackson",
    senderEmail: "c.jackson@college.net",
    status: TicketStatus.open,
    category: "Refund Request",
    daysAgo: 4,
    assignedToId: null,
  },
  {
    subject: "Duplicate charge for the same subscription",
    body: "Hello,\n\nMy credit card statement shows two charges of $149 on 1 May for the same Pro Monthly subscription. I only authorised one payment. Please refund the duplicate charge immediately.\n\nElijah White",
    senderName: "Elijah White",
    senderEmail: "e.white@uni.edu",
    status: TicketStatus.inProgress,
    category: "Refund Request",
    daysAgo: 3,
    assignedToId: SUBROTO,
  },
  {
    subject: "Cancelled within 7-day window but refund has not arrived",
    body: "Hi support,\n\nI cancelled my subscription on 22 April, within the 7-day money-back guarantee period. Today is 2 May and I still have not received the refund. My bank confirms no pending transaction from you.\n\nAmelia Harris",
    senderName: "Amelia Harris",
    senderEmail: "a.harris@student.edu",
    status: TicketStatus.open,
    category: "Refund Request",
    daysAgo: 10,
    assignedToId: null,
  },
  {
    subject: "Refund for live workshop – instructor did not attend",
    body: "Hello,\n\nI paid £79 for the 'Advanced SQL Live Workshop' on 28 April. The instructor did not show up and the session was never rescheduled. I would like a full refund for the missed session.\n\nOliver Martin",
    senderName: "Oliver Martin",
    senderEmail: "o.martin@college.net",
    status: TicketStatus.inProgress,
    category: "Refund Request",
    daysAgo: 5,
    assignedToId: SUBROTO,
  },
  {
    subject: "Charged after I cancelled my subscription",
    body: "Hi,\n\nI cancelled my subscription on 15 April via account settings and received a cancellation confirmation email. I was still charged $99 on 1 May. Please refund the charge and confirm cancellation.\n\nHarper Thompson",
    senderName: "Harper Thompson",
    senderEmail: "h.thompson@university.edu",
    status: TicketStatus.open,
    category: "Refund Request",
    daysAgo: 2,
    assignedToId: null,
  },
  {
    subject: "Partial refund request – completed only 8% of the course",
    body: "Hello,\n\nI purchased an annual plan 3 weeks ago but due to a change in job responsibilities the course is no longer relevant. I have only completed 8% of the content. I would like a pro-rated refund.\n\nBenjamin Garcia",
    senderName: "Benjamin Garcia",
    senderEmail: "b.garcia@student.edu",
    status: TicketStatus.closed,
    category: "Refund Request",
    daysAgo: 50,
    assignedToId: GOUTOM,
  },
  {
    subject: "Refund for persistent technical issues that made the course unusable",
    body: "Hi support,\n\nI have been experiencing video playback failures on the Data Engineering course for 3 weeks. I have submitted 4 support tickets and the issue is unresolved. I cannot continue and request a refund.\n\nEvelyn Lee",
    senderName: "Evelyn Lee",
    senderEmail: "e.lee@college.net",
    status: TicketStatus.inProgress,
    category: "Refund Request",
    daysAgo: 7,
    assignedToId: SUBROTO,
  },
  {
    subject: "Wrong currency charged – requesting refund and re-charge in GBP",
    body: "Hello,\n\nMy account is set to GBP but I was charged $129 USD instead of £99 GBP. The currency conversion cost me an extra £8 in bank fees. Please refund in USD and re-charge in GBP.\n\nAiden Clark",
    senderName: "Aiden Clark",
    senderEmail: "a.clark@uni.edu",
    status: TicketStatus.open,
    category: "Refund Request",
    daysAgo: 3,
    assignedToId: null,
  },
  {
    subject: "Annual plan refund request – want to switch to monthly billing",
    body: "Hi,\n\nI purchased an annual plan last month but I would prefer to pay monthly to manage my budget better. I understand I may lose some discount. Could I get a refund and switch to the monthly plan?\n\nAbigail Lewis",
    senderName: "Abigail Lewis",
    senderEmail: "ab.lewis@student.edu",
    status: TicketStatus.closed,
    category: "Refund Request",
    daysAgo: 40,
    assignedToId: GOUTOM,
  },
  {
    subject: "Refund request with employer reimbursement documentation",
    body: "Hello,\n\nMy employer requires the original invoice and a letter confirming the course was not completed for their reimbursement process. I also need a refund of the $199 I paid. Order: ORD-20240315.\n\nLogan Hall",
    senderName: "Logan Hall",
    senderEmail: "l.hall@college.net",
    status: TicketStatus.inProgress,
    category: "Refund Request",
    daysAgo: 12,
    assignedToId: SUBROTO,
  },
  {
    subject: "Course was removed from the platform after I purchased it",
    body: "Hi,\n\nThe 'Ruby on Rails' course I purchased in January has been removed from the platform without notice. I can no longer access any of the content. I request a full refund. Order: ORD-20240110.\n\nEmma Johnson",
    senderName: "Emma Johnson",
    senderEmail: "emma.j@student.edu",
    status: TicketStatus.open,
    category: "Refund Request",
    daysAgo: 5,
    assignedToId: null,
  },
  {
    subject: "Refund for duplicate account charges during sign-up",
    body: "Hello,\n\nWhen I first registered the payment page timed out and I submitted twice, resulting in two charges of $49. I only need one account. Please refund the second charge. Both transactions are on 30 April.\n\nLiam Williams",
    senderName: "Liam Williams",
    senderEmail: "l.williams@college.net",
    status: TicketStatus.closed,
    category: "Refund Request",
    daysAgo: 35,
    assignedToId: GOUTOM,
  },
  {
    subject: "Subscription renewed without authorisation",
    body: "Hi support,\n\nI did not receive the 30-day renewal reminder email your policy promises. My annual subscription renewed yesterday for $299 without any warning. I would like a refund as I intended to cancel.\n\nOlivia Brown",
    senderName: "Olivia Brown",
    senderEmail: "olivia.b@university.edu",
    status: TicketStatus.inProgress,
    category: "Refund Request",
    daysAgo: 2,
    assignedToId: SUBROTO,
  },
  {
    subject: "Refund – course language was different from what was advertised",
    body: "Hello,\n\nThe course listing stated 'Taught in English' but the videos are in Hindi with English subtitles. I do not learn well with subtitles. I purchased based on the language description and request a refund.\n\nNoah Davis",
    senderName: "Noah Davis",
    senderEmail: "n.davis@student.edu",
    status: TicketStatus.open,
    category: "Refund Request",
    daysAgo: 6,
    assignedToId: null,
  },
  {
    subject: "Medical leave – refund for unused course access",
    body: "Hi,\n\nI have been hospitalised since 10 April and have been unable to study. I have a doctor's letter confirming my admission. I only completed 15% of the course and request a refund for the unused access.\n\nAva Martinez",
    senderName: "Ava Martinez",
    senderEmail: "ava.m@college.net",
    status: TicketStatus.inProgress,
    category: "Refund Request",
    daysAgo: 14,
    assignedToId: SUBROTO,
  },
  {
    subject: "Refund for gift voucher that was never redeemed",
    body: "Hello,\n\nI purchased a gift voucher worth $79 as a birthday present in March. The recipient never redeemed it (the expiry is in June). I would like to request a refund for the unredeemed voucher. Voucher code: GIFT-2024-441.\n\nIsabella Garcia",
    senderName: "Isabella Garcia",
    senderEmail: "i.garcia@uni.edu",
    status: TicketStatus.open,
    category: "Refund Request",
    daysAgo: 4,
    assignedToId: null,
  },
  {
    subject: "Pro plan features were unavailable as described – requesting refund",
    body: "Hi support,\n\nI upgraded to Pro specifically for the 'Priority 1:1 coaching' feature. When I tried to book a session I was told this feature is 'coming soon'. I want a refund of the Pro upgrade cost.\n\nSophia Rodriguez",
    senderName: "Sophia Rodriguez",
    senderEmail: "s.rodriguez@student.edu",
    status: TicketStatus.closed,
    category: "Refund Request",
    daysAgo: 55,
    assignedToId: GOUTOM,
  },
  {
    subject: "Refund request – instructor left the platform after I enrolled",
    body: "Hello,\n\nI enrolled specifically because of the instructor Dr. Kim. She left the platform two weeks after I joined and her courses have not been updated since. I feel the course is now without proper support.\n\nMason Wilson",
    senderName: "Mason Wilson",
    senderEmail: "m.wilson@college.net",
    status: TicketStatus.inProgress,
    category: "Refund Request",
    daysAgo: 9,
    assignedToId: SUBROTO,
  },
  {
    subject: "Course not compatible with my screen reader – refund requested",
    body: "Hi,\n\nI use NVDA screen reader due to a visual impairment. The course content is not accessible – images have no alt text, videos have no audio description. I cannot use the course and request a full refund.\n\nMia Anderson",
    senderName: "Mia Anderson",
    senderEmail: "mia.a@university.edu",
    status: TicketStatus.open,
    category: "Refund Request",
    daysAgo: 3,
    assignedToId: null,
  },
  {
    subject: "Double charged due to payment gateway timeout",
    body: "Hello,\n\nThe payment gateway timed out on my first attempt so I submitted again. Both transactions went through — I was charged $149 twice on the same day. Bank reference numbers: TXN-554123 and TXN-554124.\n\nLucas Thomas",
    senderName: "Lucas Thomas",
    senderEmail: "l.thomas@student.edu",
    status: TicketStatus.inProgress,
    category: "Refund Request",
    daysAgo: 5,
    assignedToId: SUBROTO,
  },
  {
    subject: "Refund for corporate training – company project was cancelled",
    body: "Hi,\n\nI purchased 5 team licences for the DevOps Fundamentals course for an internal training initiative. The project has since been cancelled and none of the accounts have been accessed. Please refund all 5 licences.\n\nCharlotte Jackson",
    senderName: "Charlotte Jackson",
    senderEmail: "c.jackson@college.net",
    status: TicketStatus.open,
    category: "Refund Request",
    daysAgo: 7,
    assignedToId: null,
  },
  {
    subject: "Changed mind within 2 hours of purchase",
    body: "Hello,\n\nI purchased the Graphic Design course about 2 hours ago but I have decided it is not the right fit for my career goals. I have not watched any content. Could I get a refund under the cooling-off period?\n\nElijah White",
    senderName: "Elijah White",
    senderEmail: "e.white@uni.edu",
    status: TicketStatus.closed,
    category: "Refund Request",
    daysAgo: 30,
    assignedToId: GOUTOM,
  },
  {
    subject: "Promotional price not honoured at checkout – requesting refund",
    body: "Hi support,\n\nYour homepage showed a flash sale price of $49 for the Data Science course. When I clicked through and checked out I was charged the full price of $149. I have a screenshot of the offer.\n\nAmelia Harris",
    senderName: "Amelia Harris",
    senderEmail: "a.harris@student.edu",
    status: TicketStatus.inProgress,
    category: "Refund Request",
    daysAgo: 4,
    assignedToId: SUBROTO,
  },
  {
    subject: "Enrolled in wrong cohort by mistake – refund and re-enrolment",
    body: "Hello,\n\nI enrolled in the March cohort instead of the May cohort. The March cohort has already started and I cannot join mid-way. Could I get a refund and be re-enrolled in the May cohort at the same price?\n\nOliver Martin",
    senderName: "Oliver Martin",
    senderEmail: "o.martin@college.net",
    status: TicketStatus.open,
    category: "Refund Request",
    daysAgo: 2,
    assignedToId: null,
  },
  {
    subject: "Account was deactivated but subscription still renewed",
    body: "Hi,\n\nMy account was deactivated by admin in February due to a billing dispute (since resolved). While deactivated, my subscription renewed in March and April — 2 months I could not access. Please refund both charges.\n\nHarper Thompson",
    senderName: "Harper Thompson",
    senderEmail: "h.thompson@university.edu",
    status: TicketStatus.inProgress,
    category: "Refund Request",
    daysAgo: 11,
    assignedToId: SUBROTO,
  },
  {
    subject: "Course certificate not internationally recognised – refund",
    body: "Hello,\n\nI enrolled based on the claim that the certificate is recognised internationally. My employer in Germany says they have not heard of the accrediting body. This was a key factor in my purchase decision.\n\nBenjamin Garcia",
    senderName: "Benjamin Garcia",
    senderEmail: "b.garcia@student.edu",
    status: TicketStatus.open,
    category: "Refund Request",
    daysAgo: 6,
    assignedToId: null,
  },
  {
    subject: "Two payments processed on the same day for one order",
    body: "Hi support,\n\nI can see two debit card charges of £89 processed on 29 April. Both transactions reference the same order number ORD-20240429. Please confirm which is the duplicate and refund it.\n\nEvelyn Lee",
    senderName: "Evelyn Lee",
    senderEmail: "e.lee@college.net",
    status: TicketStatus.closed,
    category: "Refund Request",
    daysAgo: 45,
    assignedToId: GOUTOM,
  },
  {
    subject: "Refund for unused course bundle – only one module was relevant",
    body: "Hello,\n\nI purchased the Full Stack Bundle expecting to need all modules. After reviewing the content, only the CSS module was relevant to my project. I would like a refund for the unused portions of the bundle.\n\nAiden Clark",
    senderName: "Aiden Clark",
    senderEmail: "a.clark@uni.edu",
    status: TicketStatus.inProgress,
    category: "Refund Request",
    daysAgo: 8,
    assignedToId: SUBROTO,
  },
  {
    subject: "Changed career path – course content no longer relevant",
    body: "Hi,\n\nI enrolled in the Finance & Accounting course while planning to pursue a finance career. I have since changed direction to software engineering. I have completed less than 5% of the content and request a refund.\n\nAbigail Lewis",
    senderName: "Abigail Lewis",
    senderEmail: "ab.lewis@student.edu",
    status: TicketStatus.open,
    category: "Refund Request",
    daysAgo: 3,
    assignedToId: null,
  },
];

async function main() {
  const data = tickets.map((t, i) => ({
    subject: t.subject,
    body: t.body,
    senderName: t.senderName,
    senderEmail: t.senderEmail,
    status: t.status,
    category: t.category,
    messageId: `seed2-${String(i + 1).padStart(3, "0")}@helpdesk.example.com`,
    assignedToId: t.assignedToId,
    createdAt: daysAgo(t.daysAgo),
    updatedAt: daysAgo(Math.max(0, t.daysAgo - 1)),
  }));

  const result = await db.ticket.createMany({ data, skipDuplicates: true });
  console.log(`Created ${result.count} tickets (${tickets.length - result.count} skipped as duplicates)`);
}

main()
  .catch((err) => {
    console.error(err);
    process.exitCode = 1;
  })
  .finally(async () => {
    await db.$disconnect();
  });
